name: Rust tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: icepuma/rust-action@master
        with:
          args: cargo fmt -- --check && cargo clippy -- -Dwarnings && cargo test
